language: java
sudo: true
addons:
  apt:
    sources:
      - google-chrome
    packages:
    - oracle-java8-installer
    - oracle-java8-set-default
    - google-chrome-stable

env:
  - TEST_ENV=false

install: true

before_install:
  - npm i npm@latest -g
  - cd ./coderadar-app/
  - npm install
  - npm install -g @angular/cli
  - cd ../

#stages:
#
#- name: build

cache:
  directories:
    - ./node_modules

#- name: release
#  if: branch = master AND type IN (push)

jobs:
  include:

  - stage: build
    script:
      - ./gradlew --stacktrace build
  - stage: test
    if: env(TEST_ENV) = true
    script:
      - cd ./coderadar-app/
      - ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
      - ng e2e --protractor-config='e2e/protractor-ci.conf.js'

#  - stage: release
#    script:
#   - "cd coderadar-server/coderadar-core"
#   - "../../gradlew --console=plain clean preparePages"
#   - "../../gradlew gitPublishPush --stacktrace"
#   - "../../gradlew bintrayUpload --stacktrace"

