databaseChangeLog:
  - changeSet:
      id: 3
      author: thombergs
      changes:
        - createTable:
            tableName: analyzer_configuration
            schemaName: public
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: project_id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: analyzer_name
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: enabled
                  type: boolean
                  constraints:
                    nullable: false
        - addPrimaryKey:
            constraintName: pk_acon_id
            schemaName: public
            tableName: analyzer_configuration
            columnNames: id
        - addUniqueConstraint:
            constraintName: uk_acon_id
            schemaName: public
            tableName: analyzer_configuration
            columnNames: id
        - addForeignKeyConstraint:
            constraintName: fk_acon_proj
            baseColumnNames: project_id
            baseTableName: analyzer_configuration
            referencedColumnNames: id
            referencedTableName: project
        - createIndex:
            indexName: idx_acon_project_id
            schemaName: public
            tableName: analyzer_configuration
            columns:
            - column:
                name: project_id
        - createSequence:
            schemaName: public
            sequenceName: seq_acon_id


