runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored

env_variables:
  SPRING_PROFILES_ACTIVE: "appengine"

readiness_check:
  path: "/health"
  check_interval_sec: 10
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 60
